In [1]:
import os
print("Welcome to jupyter notebook")

Welcome to jupyter notebook


In [2]:
os.getcwd()

'D:\\Rahul Golani\\Web Application To Consume Prediction Models'

# Heading

In [3]:
%lsmagic


Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [4]:
%%time print("Hi")

UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [5]:
%time print("i")

i
Wall time: 992 µs


In [6]:
import numpy as np

In [7]:
pylist=list(range(1000000))

In [8]:
arr=np.arange(1000000)

In [9]:
%time for _ in range(10): [item*3 for item in pylist]

Wall time: 1.47 s


In [10]:
%time for _ in range(10): arr=arr*3

Wall time: 91.8 ms


In [11]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [12]:
type(arr)

numpy.ndarray

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros(4,5)

TypeError: data type not understood

In [15]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.ones(4).dtype

dtype('float64')

In [20]:
array1=np.array([[1,2,3,4],[5,6,7,8]])

In [21]:
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
array1.dtype

dtype('int32')

In [23]:
type(array1)

numpy.ndarray

In [24]:
array1+array1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [25]:
array1*array1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])